### ISSUE TITLE
MissingFieldException 'checksName' for Freestyle project

### ISSUE THREAD

**Issue by zencode1** [jenkinsci/junit-plugin#222]
After upgrading JUnit plugin to 1.44 Jenkins warns of unreadable data for freestyle projects that use publish JUnit results.

```
Project type: hudson.model.FreeStyleBuild
Error: MissingFieldException: No field 'checksName' found in class 'hudson.tasks.junit.TestResultAction
```

Since I don't use any custom names I chose to discard the old data.  The same day, I upgraded JUnit to 1.45.  Unrelated but I mention this just in case, I was finally able to upgrade Jenkins past 2.263 (couldn't due to the div vs tables change).

This morning, the unreadable data messages are shown again.  This time, shown using Jenkins 2.269 formatting.

```
Project type:
Error: MissingFieldException: Field not found in class. ---- Debugging information ---- message : Field not found in class. field : hudson.tasks.junit.TestResultAction.checksName
```

I clicked "Discard Unreadable Data".  Is this going to continue to happen every day?

**Comment by timja** [comment]
If I knew how to reproduce it I could fix it, but I just can't seem to reproduce this on demand.

(We have this happening in our production instance too)

I can't see why `checksName` is expected to be on that class =/
I'm misunderstanding some Jenkins-ism I think. but can't see what

> I clicked "Discard Unreadable Data". Is this going to continue to happen every day?

for now yes probably, shouldn't cause an actual issue though

**Comment by timja** [comment]
Looks to be caused by https://github.com/jenkinsci/junit-plugin/pull/199/files#diff-4fa8f2162a640cc3f024dadbffc9b442ab73e2afd30e5030ec0088ac300371e5L78

This should go away if you reconfigure your job
